//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFI_PAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visita
    {
        public System.Guid ID { get; set; }
        public int CantidadVisitas { get; set; }
    
        public virtual Libro Libro { get; set; }
        public virtual Perfil Perfil { get; set; }
    }
}
